apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bjznwsb6h-go
  janus-idp.io/tekton: bjznwsb6h-go
  backstage.io/kubernetes-id: bjznwsb6h-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bjznwsb6h-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
